### PR TITLE
Binary Search Tree insertion & displaying inorder traversal is added

### PR DESCRIPTION
**Pull request by HackMEAny**
Binary Search Tree insertion & displaying inorder traversal is done using Python3

### CODE REVIEW

**Comment by Chayan-19** [comment]
@HackMEAny thanks for contributing, please add a proper description associated with your PR.
A description can include the files you changed, some facts about your code etc.

**Comment by HackMEAny** [comment]
The description is added will it be accepted now?

**Comment by chayan-chawra-1903** [comment]
@HackMEAny thank you for contributing to this repo. please add a proper description of your PR from the next time. Adding the file path with the file name is considered as a good practise. Also adding a 2 line description about how the algorithm works or attaching the output the algorithm produces would be a good way to go. 
If you are enjoying contributing to this repo, please star the repo!

**Comment by chayan-chawra-1903** [comment]
@HackMEAny thank you for contributing to this repo. please add a proper description of your PR from the next time. Adding the file path with the file name is considered as a good practise. Also adding a 2 line description about how the algorithm works or attaching the output the algorithm produces would be a good way to go. 
If you are enjoying contributing to this repo, please star the repo!

**Pull request merged**
